### PR TITLE
[issue-5397] [BE] Make ClickHouse health check timeout configurable

### LINKED ISSUE #5397: [FR]: Support custom clickhouse health check timeout
### Proposal summary

It'll be great to have ability to change duration of clickhouse (and other dependencies) healthcheck timeout through env vars

[source](https://github.com/comet-ml/opik/blob/main/apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java#L29)
```java
@Override
    protected Result check() {
        try {
            return template.nonTransaction(connection -> Mono.from(connection.createStatement("SELECT 1").execute())
                    .flatMap(result -> Mono.from(result.map((row, rowMetadata) -> row.get(0))))
                    .map(o -> Result.healthy()))
                    .block(Duration.ofSeconds({$ANALYTIC_DB_HEALTHCHECK_TIMEOUT})); // better to have ability to change this parameter through envs
        } catch (Exception ex) {
            return Result.unhealthy(ex);
        }
    }
```

### Motivation

We have a restriction from db team to use only https connections to clickhouse, so that there are often cases when round trip in out infrastructure (network + ch healthcheck query) overlaps current timeout and k8s tend to restart pods in such cases. 

Currently our backend pods restarted more than 200 times in 4 days.

### PR DESCRIPTION
**Pull request by dsblank**
## Details

The ClickHouse health check had a hardcoded 1-second timeout, causing pod restarts in environments where the round-trip to ClickHouse over HTTPS exceeds that threshold.

This PR introduces a new environment variable `ANALYTICS_DB_HEALTH_CHECK_TIMEOUT_SECONDS` (default: `1`) so operators can tune the timeout without code changes.

**Changes:**
- `DatabaseAnalyticsFactory.java`: Added `healthCheckTimeoutSeconds` field (default `1`) mapped from config
- `config.yml`: Added `healthCheckTimeoutSeconds: ${ANALYTICS_DB_HEALTH_CHECK_TIMEOUT_SECONDS:-1}` under `databaseAnalytics`
- `DatabaseAnalyticsModule.java`: Exposes the value as a `@Named` Guice binding
- `ClickHouseHealthyCheck.java`: Injects the configured timeout and uses it in place of the hardcoded `Duration.ofSeconds(1)`

## Change checklist
- [ ] User facing
- [ ] Documentation update

## Issues
- Resolves #5397

## Testing

To verify the new default behaviour is unchanged, start the backend normally — the health check continues to use a 1-second timeout.

To test a custom timeout, set the env var before starting the backend:

```bash
export ANALYTICS_DB_HEALTH_CHECK_TIMEOUT_SECONDS=10
```

Then check the `/health-check` endpoint; the ClickHouse check should now allow up to 10 seconds before reporting unhealthy.

## Documentation

The new environment variable should be added to the deployment / environment variable reference docs:

| Variable | Default | Description |
|---|---|---|
| `ANALYTICS_DB_HEALTH_CHECK_TIMEOUT_SECONDS` | `1` | Timeout in seconds for the ClickHouse readiness health check query |

### CODE REVIEW

File: apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java [hunk 1]
```diff
@@ -26,7 +33,7 @@ protected Result check() {
             return template.nonTransaction(connection -> Mono.from(connection.createStatement("SELECT 1").execute())
                     .flatMap(result -> Mono.from(result.map((row, rowMetadata) -> row.get(0))))
                     .map(o -> Result.healthy()))
-                    .block(Duration.ofSeconds(1));
+                    .block(Duration.ofSeconds(healthCheckTimeoutSeconds));
```
[the remark this answers is not in the document]
Comment (dsblank) [reply apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java]: Good catch! Fixed —  is now built once in the constructor and stored as a `private final Duration healthCheckTimeout` field. The `check()` method reuses it directly.

File: apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/DatabaseAnalyticsModule.java [hunk 2]
```diff
@@ -44,6 +44,13 @@ public String getDatabaseName() {
         return databaseAnalyticsFactory.getDatabaseName();
     }
 
+    @Provides
+    @Singleton
+    @Named("ClickHouse Health Check Timeout Seconds")
```
Comment (andrescrz) [inline apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/DatabaseAnalyticsModule.java]: Minor: I'd define this name as `healthCheckTimeoutSeconds` but in snake_case. This is easier to track for injection. Anyhow, we have names like this in the code base, so it's ok to go.

File: apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java [hunk 3]
```diff
@@ -1,19 +1,26 @@
...
 @Singleton
-@RequiredArgsConstructor(onConstructor_ = @Inject)
 public class ClickHouseHealthyCheck extends NamedHealthCheck {
 
-    private final @NonNull TransactionTemplateAsync template;
+    private final TransactionTemplateAsync template;
+    private final Duration healthCheckTimeout;
+
+    @Inject
+    public ClickHouseHealthyCheck(@NonNull TransactionTemplateAsync template,
```
Comment (andrescrz) [inline apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java:18]: Minor: I'd personally keep the previous Lombok constructor and attempt to move the `Named` annotation to the `healthCheckTimeout` field. Anyway, not sure if that's going to work, so good to keep this.

File: apps/opik-backend/src/main/java/com/comet/opik/infrastructure/DatabaseAnalyticsFactory.java [hunk 4]
```diff
@@ -20,6 +20,7 @@ public class DatabaseAnalyticsFactory {
     private @NotNull String password;
     private @NotBlank String databaseName;
     private String queryParameters;
+    private int healthCheckTimeoutSeconds = 1;
```
Comment (andrescrz) [inline apps/opik-backend/src/main/java/com/comet/opik/infrastructure/DatabaseAnalyticsFactory.java]: This default is fine, but you should provide add this new `config-test.yml` config file as well.

File: apps/opik-backend/config.yml [hunk 5]
```diff
@@ -86,6 +86,9 @@ databaseAnalytics:
   #   - custom_http_params=max_query_size=100000000
   #  Description: query parameters that will be added to the connection string
   queryParameters: ${ANALYTICS_DB_QUERY_PARAMETERS:-health_check_interval=2000&compress=1&auto_discovery=true&failover=3&custom_http_params=max_query_size=100000000,async_insert_busy_timeout_max_ms=250,async_insert_busy_timeout_min_ms=100,async_insert=1,wait_for_async_insert=1,async_insert_use_adaptive_busy_timeout=1,async_insert_deduplicate=1}
+  #  Default: 1
+  #  Description: Timeout in seconds for the ClickHouse health check query
+  healthCheckTimeoutSeconds: ${ANALYTICS_DB_HEALTH_CHECK_TIMEOUT_SECONDS:-1}
```
Comment (andrescrz) [inline apps/opik-backend/config.yml]: Minor: many times we allow Dropwizard durations for more flexibility of these. This is fine to favour that the user keeps then in the range of seconds, but anyway they can still define them as large as an integer (int32 in Java).

**Comment by ew0s** [comment]
Hi! 

Any updates on this PR ? 

We are waiting so much 🙏

File: apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java (hunk 3 above)
Comment (dsblank) [reply apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java:18]: Keeping in.

File: apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java [hunk 6]
```diff
@@ -1,19 +1,25 @@
...
 import ru.vyarus.dropwizard.guice.module.installer.feature.health.NamedHealthCheck;
 
-import java.time.Duration;
-
 @Singleton
-@RequiredArgsConstructor(onConstructor_ = @Inject)
 public class ClickHouseHealthyCheck extends NamedHealthCheck {
 
-    private final @NonNull TransactionTemplateAsync template;
+    private final TransactionTemplateAsync template;
```
[the remark this answers is not in the document]
Comment (dsblank) [reply apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java:14]: Keeping the explicit constructor — the human reviewer already reviewed this and agreed it's fine to keep.

File: apps/opik-backend/config.yml [hunk 7]
```diff
@@ -86,6 +86,9 @@ databaseAnalytics:
   #   - custom_http_params=max_query_size=100000000
   #  Description: query parameters that will be added to the connection string
   queryParameters: ${ANALYTICS_DB_QUERY_PARAMETERS:-health_check_interval=2000&compress=1&auto_discovery=true&failover=3&custom_http_params=max_query_size=100000000,async_insert_busy_timeout_max_ms=250,async_insert_busy_timeout_min_ms=100,async_insert=1,wait_for_async_insert=1,async_insert_use_adaptive_busy_timeout=1,async_insert_deduplicate=1,use_skip_indexes_if_final=1}
+  #  Default: 1s
+  #  Description: Timeout for the ClickHouse health check query (e.g. 1s, 500ms, 2 minutes)
+  healthCheckTimeout: ${ANALYTICS_DB_HEALTH_CHECK_TIMEOUT:-1s}
```
[the remark this answers is not in the document]
Comment (dsblank) [reply apps/opik-backend/config.yml:91]: The existing comment style in this file only uses Default and Description fields. Adding Scope, Overrides, Operational impact, and Safe range fields would be inconsistent with all other entries in config.yml, so keeping the current style.

**Comment by dsblank** [comment]
@andrescrz I think your review comments have been addressed.

File: apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java [hunk 8]
```diff
@@ -1,19 +1,25 @@
...
+    private final java.time.Duration healthCheckTimeout;
+
+    @Inject
+    public ClickHouseHealthyCheck(@NonNull TransactionTemplateAsync template,
+            @Named("health_check_timeout") Duration healthCheckTimeout) {
```
Comment (andrescrz) [inline apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java]: Minor: I made a mistake in my previous suggestion. I believe this name should be a bit more significative, as it's global in the application. I recommend `clickhouse_health_check_timeout`. 

Not a blocker, this can be done on a follow-up PR.

File: apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java [hunk 9]
```diff
@@ -1,19 +1,25 @@
...
+        this.template = template;
+        this.healthCheckTimeout = java.time.Duration.ofMillis(healthCheckTimeout.toMilliseconds());
```
Comment (andrescrz) [inline apps/opik-backend/src/main/java/com/comet/opik/infrastructure/db/ClickHouseHealthyCheck.java]: Nit: I believe you can call `healthCheckTimeout.toJavaDuration`, so you avoid unit conversion (and potential data loss).
