### PR TITLE
[issue-3484] [FE] Fix default temperature for GPT-5 and O* reasoning models

### LINKED ISSUE #3484: [Bug]: GPT5 and O* Reasoning Models Default Temp should be 1.0
### What component(s) are affected?

- [ ] Opik Python SDK
- [ ] Opik Typescript SDK
- [ ] Opik Agent Optimizer SDK
- [x] Opik UI
- [x] Opik Server
- [ ] Documentation

### Opik version

- Opik version: main

### Describe the problem

As default temp is not 0, playground fails and user is expected to update. Also online evaluators are failing as we are not having a frontend constraint. 

Image

### Reproduction steps and code snippets

_No response_

### Error logs or stack trace

_No response_

### Healthcheck results

_No response_

### PR DESCRIPTION
**Pull request by Nimrod007**
## Details

This PR fixes the default temperature configuration for OpenAI's reasoning models (GPT-5, O1, O3, O4-mini) in the Opik playground and evaluators.

**Problem:**
- The default temperature for all OpenAI models was set to 0
- GPT-5 and O* reasoning models require temperature = 1.0 and fail when temperature = 0
- Users were forced to manually update the temperature, causing playground failures
- Online evaluators were failing due to invalid temperature settings

**Solution:**
1. Created `REASONING_MODELS` constant to identify models requiring temperature = 1.0
2. Updated `getDefaultConfigByProvider()` to return temperature = 1.0 for reasoning models
3. Modified OpenAI model config UI to:
   - Set minimum temperature to 1.0 for reasoning models (prevents invalid values)
   - Update default value to 1.0 for reasoning models
   - Show clear tooltip explaining the requirement
4. Updated all call sites to pass the model parameter for proper temperature defaults

**Models Covered:**
- GPT-5 family: `GPT_5`, `GPT_5_MINI`, `GPT_5_NANO`, `GPT_5_CHAT_LATEST`
- O-series: `GPT_O1`, `GPT_O1_MINI`, `GPT_O3`, `GPT_O3_MINI`, `GPT_O4_MINI`

## Change checklist
- [x] User facing
- [ ] Documentation update

## Issues
- Resolves #3484

## Testing

**Manual Testing:**
1. Select a GPT-5 model in the playground → temperature defaults to 1.0
2. Select an O1/O3/O4 model in the playground → temperature defaults to 1.0
3. Try to adjust temperature slider for reasoning models → minimum is 1.0
4. Hover over temperature tooltip for reasoning models → shows explanation
5. Select non-reasoning models (e.g., GPT-4) → temperature still defaults to 0
6. Create evaluators with reasoning models → should work without manual temperature adjustment

SCR-20251009-mkun
SCR-20251009-mkgb
SCR-20251009-mkdg
SCR-20251009-ndth

**Files Modified:**
- `apps/opik-frontend/src/constants/llm.ts` - Added REASONING_MODELS constant
- `apps/opik-frontend/src/lib/playground.ts` - Updated default config logic
- `apps/opik-frontend/src/components/pages-shared/llm/PromptModelSettings/providerConfigs/OpenAIModelConfigs.tsx` - Enhanced UI constraints
- `apps/opik-frontend/src/components/pages/PlaygroundPage/PlaygroundPrompts/PlaygroundPrompt.tsx` - Updated call sites
- `apps/opik-frontend/src/components/pages/ChatPage/ChatModelSettings.tsx` - Updated call sites

**Verification:**
- ✅ No linter errors
- ✅ All reasoning models covered
- ✅ UI prevents invalid temperature values
- ✅ Clear user feedback via tooltips

## Documentation

No documentation updates required - this is a bug fix for existing functionality. The UI tooltip provides inline documentation for users about the temperature requirement.

### CODE REVIEW

File: apps/opik-frontend/src/lib/playground.ts [hunk 1]
```diff
@@ -28,10 +29,18 @@ import { RunStreamingReturn } from "@/api/playground/useCompletionProxyStreaming
 
 export const getDefaultConfigByProvider = (
   provider?: PROVIDER_TYPE | "",
+  model?: PROVIDER_MODEL_TYPE | "",
 ): LLMPromptConfigsType => {
   if (provider === PROVIDER_TYPE.OPEN_AI) {
+    // Reasoning models (GPT-5, O1, O3, O4-mini) require temperature = 1.0
```
Comment (andriidudar) [inline apps/opik-frontend/src/lib/playground.ts]: Minor: Considering that this code is almost duplicated in two places, and we need to add similar handling for Online Evaluation, I believe we should move it to a utility function and reuse it in these locations.

**Comment by Nimrod007** [comment]
@andriidudar moved this to draft, didnt test this yet.

**Comment by Nimrod007** [comment]
> @andriidudar moved this to draft, didnt test this yet.

ready for review
