### PR TITLE
[issue-4722] [FE] Fix pretty input view with system message last

### LINKED ISSUE #4722: [Bug]: Failed Pretty Input when System Message Last
### What component(s) are affected?

- [ ] Opik Python SDK
- [ ] Opik Typescript SDK
- [ ] Opik Agent Optimizer SDK
- [x] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 1.7.36

### Describe the problem

Our input has a system message last. This prevents the pretty view from loading. Ideally, the pretty version would show the last human message in the input.

### Reproduction steps and code snippets

_No response_

### Error logs or stack trace

_No response_

### Healthcheck results

_No response_

### PR DESCRIPTION
**Pull request by collincunn**
## Details
Fixed a bug in the `prettifyOpenAIMessageLogic` function that caused the pretty input view to fail or display incorrect content when a system message appeared last in the messages array.

The function now filters the messages array to select only messages with `role === "user"` before taking the last message. This ensures that the pretty view always displays the most recent user message, regardless of where system messages appear in the conversation history.

**Changes:**
- Updated `prettifyOpenAIMessageLogic` in `apps/opik-frontend/src/lib/traces.ts` to filter for user messages before selection
- Added comprehensive test coverage for edge cases including:
  - System message appearing last
  - Multiple system messages interspersed with user messages
  - Only system messages present (graceful fallback)
- Updated existing tests to include the `role` field in message objects

**Behavior:**
- ✅ When user messages exist: Returns the last user message content
- ✅ When no user messages exist: Returns `undefined`, allowing subsequent prettifier functions to handle the message
- ✅ Maintains backward compatibility with existing message formats

## Change checklist
- [x] User facing
- [ ] Documentation update

## Issues
- Resolves #4722
- OPIK-3842

## Testing
**Unit Tests:**
- All 29 unit tests pass, including 3 new test cases specifically for this bug
- Run tests with: `npm test -- src/lib/traces.test.ts`

**Manual Testing:**
1. Create a trace with OpenAI message format where the last message has `role: "system"`
2. Navigate to the trace details page
3. Verify the pretty input view displays the last user message instead of the system message
4. Test with various message orderings (system messages at beginning, middle, and end)

**Test Coverage:**
- System message last: `"User message 2"` is displayed, not `"System instruction"`
- Mixed roles: Last user message is always selected regardless of subsequent system messages
- Only system messages: Gracefully falls back to generic prettification logic

## Documentation
No documentation updates required. This is an internal bug fix that improves existing functionality without changing the public API or user-facing behavior beyond fixing the broken pretty view

### CODE REVIEW

**Comment by CometActions** [comment]
✅ **Test environment is now available!**

**To configure additional Environment** variables for your environment, run [Deploy Opik AdHoc Environment workflow] (https://github.com/comet-ml/comet-deployment/actions/workflows/deploy_opik_adhoc_env.yaml)

### Access Information
- **URL:** https://pr-4764.dev.comet.com
- **Cluster:** comet-ml-development
- **Namespace:** pr-4764
- **Version:** 1.9.85-4764-merge-947
- **Application logs:** [View in Grafana](https://grafana.dev.comet.com/explore?schemaVersion=1&panes=%7B%22ai4%22%3A%7B%22datasource%22%3A%22P8E80F9AEF21F6940%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22expr%22%3A%22%7Bnamespace%3D%5C%22pr-4764%5C%22%7D%22%2C%22queryType%22%3A%22range%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22P8E80F9AEF21F6940%22%7D%2C%22editorMode%22%3A%22builder%22%2C%22direction%22%3A%22forward%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D%7D&orgId=1)

The deployment has completed successfully and the version has been verified.

File: apps/opik-frontend/src/lib/traces.ts [hunk 1]
```diff
@@ -212,18 +216,37 @@ const prettifyLangGraphLogic = (
...
+            humanMessages.push(lastTextContent.text);
+          }
+        }
+      }
+    }
 
     if (humanMessages.length > 0) {
-      return last(humanMessages).content;
+      return last(humanMessages);
     }
```
Comment (aadereiko) [inline apps/opik-frontend/src/lib/traces.ts:250]: This piece of code is repeated twice. Could you move to a reused function, and call it in a way that will explain what it does?

Comment (collincunn) [reply apps/opik-frontend/src/lib/traces.ts:250]: will do
