### PR TITLE
[OPIK-4417] [BE][FE] Fix incorrect usage Sum aggregation in stats

### LINKED ISSUE #5170: [Bug]: Issues with the table in the "Spans" tab
### What component(s) are affected?

- [ ] Opik Python SDK
- [ ] Opik Typescript SDK
- [ ] Opik Agent Optimizer SDK
- [x] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 1.10.11 (open source)

### Describe the problem

There are several issues when working with the table in the "Spans" tab (Observability -> Logs -> Spans).
1. Table cells change their values when sorting rows by certain columns. For example, this occurs when sorting by the "Total tokens" column.

Image

Image

2. When filtering spans by a specific criterion (e.g., by Trace ID) and selecting Sum as the aggregation method for columns such as "Total tokens", "Total input tokens", and "Total output tokens", the aggregation result is incorrect.

Image

3. The "Count" value in the "Input" column doesn't match the number of non-empty inputs.

Image

### Reproduction steps and code snippets

_No response_

### Error logs or stack trace

_No response_

### Healthcheck results

_No response_

### PR DESCRIPTION
**Pull request by JetoPistola**
## Details

image

Fixed incorrect Sum aggregation for token usage columns (total_tokens, prompt_tokens, completion_tokens) and total_estimated_cost in the spans, traces, and threads tables.

**Root cause:** The frontend was computing `Sum = count × avg`, but `avgMap(usage)` in ClickHouse only averages over rows that have the key in their usage map, while `count` includes all rows. This caused inflated sums, especially when filtering by Trace ID (traces typically have a mix of LLM spans with token usage and tool/general spans without).

**Fix:**
- **Backend**: Added `sumMap(usage) as usage_sum` to the stats queries in `SpanDAO`, `TraceDAO`, and `ThreadDAO`, and wired it through `StatsMapper` to the API response
- **Frontend**: Updated `HeaderStatistic` to use the real sum values from the backend (`usage_sum.*` for tokens, `total_estimated_cost_sum` for cost) instead of the incorrect `count × avg` approximation

## Change checklist
- [x] User facing
- [x] Documentation update

## Issues

- Resolves #5170 (bug #2)
- OPIK-4417

## Testing

- Verify Sum aggregation for Total tokens, Total input tokens, and Total output tokens columns shows correct values when filtering spans by Trace ID
- Verify Sum aggregation works correctly for traces and threads tables as well
- Verify total_estimated_cost Sum is correct (now uses real backend sum instead of count × avg)
- Verify Average aggregation is unchanged

## Documentation

N/A

### CODE REVIEW

File: apps/opik-frontend/src/components/shared/DataTableHeaders/HeaderStatistic.tsx [hunk 1]
```diff
@@ -119,23 +119,28 @@ const HeaderStatistic: React.FC<HeaderStatisticProps> = ({
...
 
-      // Round token counts to whole numbers (tokens are discrete units)
-      if (statisticKey && statisticKey.includes("tokens")) {
-        sumValue = Math.round(sumValue);
+    if (sumStatName) {
+      const sumStat = find(
+        columnsStatistic,
+        (s) =>
+          s.name === sumStatName && s.type === STATISTIC_AGGREGATION_TYPE.AVG,
+      );
```
[the remark this answers is not in the document]
Comment (JetoPistola) [reply apps/opik-frontend/src/components/shared/DataTableHeaders/HeaderStatistic.tsx:137]: No SUM type exists in the StatsType enum — only COUNT, PERCENTAGE, and AVG. The backend emits `usage_sum.*` as `AvgValueStat` (type: AVG), following the same pattern as `total_estimated_cost_sum` which already ships this way. The frontend correctly filters by `STATISTIC_AGGREGATION_TYPE.AVG` to find these stats.

🤖 *Reply posted via /address-github-pr-comments*

**Comment by CometActions** [comment]
✅ **Test environment is now available!**

**To configure additional Environment** variables for your environment, run [Deploy Opik AdHoc Environment workflow] (https://github.com/comet-ml/comet-deployment/actions/workflows/deploy_opik_adhoc_env.yaml)

### Access Information
- **URL:** https://pr-5266.dev.comet.com
- **Cluster:** comet-ml-development
- **Namespace:** pr-5266
- **Version:** 1.10.22-5266-merge-1430
- **Application logs:** [View in Grafana](https://grafana.dev.comet.com/explore?schemaVersion=1&panes=%7B%22ai4%22%3A%7B%22datasource%22%3A%22P8E80F9AEF21F6940%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22expr%22%3A%22%7Bnamespace%3D%5C%22pr-5266%5C%22%7D%22%2C%22queryType%22%3A%22range%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22P8E80F9AEF21F6940%22%7D%2C%22editorMode%22%3A%22builder%22%2C%22direction%22%3A%22forward%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D%7D&orgId=1)

The deployment has completed successfully and the version has been verified.

File: apps/opik-backend/src/main/java/com/comet/opik/domain/stats/StatsMapper.java [hunk 2]
```diff
@@ -145,7 +147,7 @@ public static Map<String, Double> getStatsUsage(Map<String, Object> stats) {
         return Optional.ofNullable(stats)
                 .map(map -> map.keySet()
                         .stream()
-                        .filter(k -> k.startsWith(USAGE))
+                        .filter(k -> k.startsWith(USAGE + "."))
                         .map(
                                 k -> Map.entry(k.substring("%s.".formatted(USAGE).length()), (Double) map.get(k)))
```
[the remark this answers is not in the document]
Comment (JetoPistola) [reply apps/opik-backend/src/main/java/com/comet/opik/domain/stats/StatsMapper.java:152]: Fixed in e38ff8731 — Added `calculateUsageSum` to `StatsUtils` which emits both `usage.*` and `usage_sum.*` expected stats. All 1,100 span tests and 1,342 trace tests now validate the prefix filter end-to-end (any leakage of `usage_sum.*` into the `usage` map would cause assertion failures).

🤖 *Reply posted via /address-github-pr-comments*

[the remark this answers is not in the document]
Comment (JetoPistola) [reply apps/opik-backend/src/main/java/com/comet/opik/domain/stats/StatsMapper.java:152]: Hey Baz

Did you see my message?

File: apps/opik-backend/src/main/java/com/comet/opik/domain/stats/StatsMapper.java [hunk 3]
```diff
@@ -145,7 +147,7 @@ public static Map<String, Double> getStatsUsage(Map<String, Object> stats) {
         return Optional.ofNullable(stats)
                 .map(map -> map.keySet()
                         .stream()
-                        .filter(k -> k.startsWith(USAGE))
+                        .filter(k -> k.startsWith(USAGE + "."))
```
Comment (andrescrz) [inline apps/opik-backend/src/main/java/com/comet/opik/domain/stats/StatsMapper.java:150]: Please explain this change and how it affects the former `usage` in addition to `usage_sum`.

File: apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java [hunk 4]
```diff
@@ -266,6 +266,13 @@ private static <T> List<ProjectStatItem<?>> getProjectStatItems(
                 .forEach(key -> stats
                         .add(new AvgValueStat("%s.%s".formatted(StatsMapper.USAGE, key), usage.get(key))));
 
+        Map<String, Double> usageSum = calculateUsageSum(usages);
+        usageSum.keySet()
+                .stream()
```
Comment (andrescrz) [inline apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java]: This operation should be done on the original stream within `calculateUsageSum` if possible.

File: apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java [hunk 5]
```diff
@@ -266,6 +266,13 @@ private static <T> List<ProjectStatItem<?>> getProjectStatItems(
...
+                .sorted()
```
Comment (andrescrz) [inline apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java]: Sorted likely not needed as each item is evaluated independently.

File: apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java [hunk 6]
```diff
@@ -266,6 +266,13 @@ private static <T> List<ProjectStatItem<?>> getProjectStatItems(
...
+                .forEach(key -> stats
+                        .add(new AvgValueStat("%s.%s".formatted(StatsMapper.USAGE_SUM, key), usageSum.get(key))));
```
Comment (andrescrz) [inline apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java]: Very nit: better use builder.

File: apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java [hunk 7]
```diff
@@ -291,6 +298,21 @@ private static <T> List<ProjectStatItem<?>> getProjectStatItems(
...
+                .filter(Objects::nonNull)
+                .map(Map::entrySet)
+                .flatMap(Collection::stream)
+                .collect(groupingBy(
+                        Map.Entry::getKey,
+                        mapping(Map.Entry::getValue, toList())))
+                .entrySet()
+                .stream()
+                .map(e -> Map.entry(e.getKey(),
+                        e.getValue().stream().mapToDouble(Long::doubleValue).sum()))
```
Comment (andrescrz) [inline apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java]: If this is a sum of long, why converting to double?

File: apps/opik-backend/src/main/java/com/comet/opik/domain/stats/StatsMapper.java (hunk 3 above)
Comment (JetoPistola) [reply apps/opik-backend/src/main/java/com/comet/opik/domain/stats/StatsMapper.java:150]: The previous `startsWith(USAGE)` matched both `usage.*` keys (e.g. `usage.completion_tokens`) and the new `usage_sum.*` keys (e.g. `usage_sum.completion_tokens`), since `"usage_sum".startsWith("usage")` is `true`. This caused `usage_sum` entries to be incorrectly processed as `usage` entries. Adding the dot makes the prefix match exact: `startsWith("usage.")` only matches `usage.*` keys, letting `usage_sum.*` fall through to its own handler below.

🤖 *Reply posted via /address-github-pr-comments*

File: apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java (hunk 7 above)
Comment (JetoPistola) [reply apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java]: The `sumMap()` ClickHouse aggregate returns map values as `Float64`, and `StatsMapper.addMapStats` reads them via `Number.doubleValue()` into `AvgValueStat` (which stores `Double`). So even though the raw per-row `usage` values are `Long`, the aggregated sum comes back as a floating-point type from ClickHouse. Using `Double` in the test keeps it consistent with what the backend actually returns. Converting `Long → Double` here (via `mapToDouble(Long::doubleValue)`) is lossless for the integer magnitudes we deal with (well within `Double`'s 53-bit mantissa).

🤖 *Reply posted via /address-github-pr-comments*

File: apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java (hunk 4 above)
Comment (JetoPistola) [reply apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java]: Fixed in f6191a215b — inlined the stream into `calculateUsageSum` which now returns `List<AvgValueStat>` directly, building stats with the builder pattern.

🤖 *Reply posted via /address-github-pr-comments*

File: apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java (hunk 5 above)
Comment (JetoPistola) [reply apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java]: Fixed in f6191a215b — removed `.sorted()` from the usage_sum stat building.

🤖 *Reply posted via /address-github-pr-comments*

File: apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java (hunk 6 above)
Comment (JetoPistola) [reply apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java]: Fixed in f6191a215b — now using `AvgValueStat.builder().name(...).value(...).type(...).build()` (with a cast due to Lombok's `@SuperBuilder` wildcard type).

🤖 *Reply posted via /address-github-pr-comments*

File: apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java (hunk 5 above)
Comment (JetoPistola) [reply apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java]: Update: moved the sort inside `calculateUsageSum` as `sorted(Map.Entry.comparingByKey())` — the span stats assertion (`SpanAssertions.assertionStatusPage`) compares lists in order (no `ignoringCollectionOrder`), so deterministic ordering is needed. Keeping it inside the method avoids the separate `.sorted()` at the call site.

🤖 *Reply posted via /address-github-pr-comments*

File: apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java [hunk 8]
```diff
@@ -291,6 +293,25 @@ private static <T> List<ProjectStatItem<?>> getProjectStatItems(
...
+                .filter(Objects::nonNull)
+                .map(Map::entrySet)
+                .flatMap(Collection::stream)
+                .collect(groupingBy(
+                        Map.Entry::getKey,
+                        mapping(Map.Entry::getValue, toList())))
+                .entrySet()
+                .stream()
+                .sorted(Map.Entry.comparingByKey())
+                .map(e -> (AvgValueStat) AvgValueStat.builder()
```
[the remark this answers is not in the document]
Comment (JetoPistola) [reply apps/opik-backend/src/test/java/com/comet/opik/api/resources/utils/StatsUtils.java:307]: Skipping — `calculateUsageSum` is already exercised through the integration tests: `FindSpansResourceTest` (1,100+ tests), `FindTracesResourceTest`, and `FindTraceThreadsResourceTest` all assert `usage_sum.*` stats via `getProjectStatItems` → `calculateUsageSum`. Adding standalone unit tests for an internal test utility helper has low value given the existing coverage.

🤖 *Reply posted via /address-github-pr-comments*

**Comment by CometActions** [comment]
✅ **Test environment is now available!**

**To configure additional Environment** variables for your environment, run [Deploy Opik AdHoc Environment workflow] (https://github.com/comet-ml/comet-deployment/actions/workflows/deploy_opik_adhoc_env.yaml)

### Access Information
- **URL:** https://pr-5266.dev.comet.com
- **Cluster:** comet-ml-development
- **Namespace:** pr-5266
- **Version:** 1.10.22-5266-merge-1449
- **Application logs:** [View in Grafana](https://grafana.dev.comet.com/explore?schemaVersion=1&panes=%7B%22ai4%22%3A%7B%22datasource%22%3A%22P8E80F9AEF21F6940%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22expr%22%3A%22%7Bnamespace%3D%5C%22pr-5266%5C%22%7D%22%2C%22queryType%22%3A%22range%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22P8E80F9AEF21F6940%22%7D%2C%22editorMode%22%3A%22builder%22%2C%22direction%22%3A%22forward%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D%7D&orgId=1)

The deployment has completed successfully and the version has been verified.

**Comment by CometActions** [comment]
✅ **Test environment is now available!**

**To configure additional Environment** variables for your environment, run [Deploy Opik AdHoc Environment workflow] (https://github.com/comet-ml/comet-deployment/actions/workflows/deploy_opik_adhoc_env.yaml)

### Access Information
- **URL:** https://pr-5266.dev.comet.com
- **Cluster:** comet-ml-development
- **Namespace:** pr-5266
- **Version:** 1.10.22-5266-merge-1458
- **Application logs:** [View in Grafana](https://grafana.dev.comet.com/explore?schemaVersion=1&panes=%7B%22ai4%22%3A%7B%22datasource%22%3A%22P8E80F9AEF21F6940%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22expr%22%3A%22%7Bnamespace%3D%5C%22pr-5266%5C%22%7D%22%2C%22queryType%22%3A%22range%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22P8E80F9AEF21F6940%22%7D%2C%22editorMode%22%3A%22builder%22%2C%22direction%22%3A%22forward%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D%7D&orgId=1)

The deployment has completed successfully and the version has been verified.

File: apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/FindTraceThreadsResourceTest.java [hunk 9]
```diff
@@ -1592,6 +1592,11 @@ private List<ProjectStats.ProjectStatItem<?>> buildExpectedThreadStats(
                             expectedStats.add(new ProjectStats.AvgValueStat("usage." + entry.getKey(),
                                     avgUsagePerThread));
                         });
+                threadUsage.entrySet().stream()
+                        .sorted(Map.Entry.comparingByKey())
+                        .forEach(entry -> expectedStats.add(
+                                new ProjectStats.AvgValueStat("usage_sum." + entry.getKey(),
```
Comment (andrescrz) [inline apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/FindTraceThreadsResourceTest.java]: Very nit: use builder as well.

Comment (JetoPistola) [reply apps/opik-backend/src/test/java/com/comet/opik/api/resources/v1/priv/FindTraceThreadsResourceTest.java]: Fixed in 7a699e8fbb — switched to `AvgValueStat.builder().name(...).value(...).type(...).build()` pattern.

🤖 *Reply posted via /address-github-pr-comments*

**Comment by JetoPistola** [comment]
> Tags stats started returning 0 Image
> 
> In staging, they work well

It appears with threads, not with traces, also on staging, a possible bug/unexpected behavior, not originated in this PR
