### PR TITLE
[issue-5621] [BE] fix: strip provider prefix in findModelPrice() for LiteLLM OTel

### LINKED ISSUE #5621: [Bug] LiteLLM OTel: model names with provider prefix (e.g. "openai/gpt-4o") not found in pricing table → zero cost on dashboard
## Summary

LiteLLM commonly sends model names in its own namespaced format via `gen_ai.request.model`, e.g.:
- `openai/gpt-4o`
- `anthropic/claude-3-5-sonnet-20241022`

Opik's runtime model price lookup does not strip the provider prefix, so these names fail all four lookup attempts and return zero cost. As a result, **all LiteLLM OTel spans record `total_estimated_cost = 0`**, causing the dashboard daily cost chart to show nothing — even though individual trace metadata may contain cost information.

**Originating report:** https://cometml.slack.com/archives/C02HPRHR2F9/p1772947523388679

## Root Cause

`CostService.parseModelPrices()` strips the provider prefix when loading the pricing JSON at startup:

```java
// CostService.java:222-225
private static String parseModelName(String modelName) {
    int prefixIndex = modelName.indexOf('/');
    return prefixIndex == -1 ? modelName : modelName.substring(prefixIndex + 1);
}
```

So the in-memory map stores keys like `gpt-4o/openai`.

But `findModelPrice()` is called at runtime with the raw model name from the span (e.g. `openai/gpt-4o`). There is no equivalent prefix-stripping at lookup time. The four fallback attempts all fail:

1. `openai/gpt-4o/openai` — not found
2. `openai-gpt-4o/openai` (dots→hyphens) — not found
3. date-suffix strip of original — no match
4. date-suffix strip of normalized — no match

Returns `DEFAULT_COST = ModelPrice.empty()` → `calculateCost()` returns 0 → `total_estimated_cost = 0` on the span → dashboard chart is empty.

## Suggested Fix

Apply the same prefix-stripping in `findModelPrice()` before the lookup attempts:

```java
private static ModelPrice findModelPrice(String modelName, String provider) {
    if (StringUtils.isBlank(modelName) || StringUtils.isBlank(provider)) {
        return DEFAULT_COST;
    }

    // Strip provider prefix if present (e.g. "openai/gpt-4o" -> "gpt-4o")
    String strippedModelName = parseModelName(modelName);

    // ... existing lookup attempts using strippedModelName instead of modelName
}
```

This is a safe, backwards-compatible change: models without a prefix are unaffected (`indexOf('/')` returns -1 → original name returned).

## Relevant Files

- `apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java` — `findModelPrice()` (line 81), `parseModelName()` (line 222)
- `apps/opik-backend/src/main/java/com/comet/opik/domain/WorkspaceMetricsDAO.java` — `GET_COSTS_DAILY` query (line 182)

### PR DESCRIPTION
**Pull request by dsblank**
## Details

LiteLLM sends model names with a provider prefix via `gen_ai.request.model` (e.g. `openai/gpt-4o`, `anthropic/claude-3-5-sonnet-20241022`). The pricing map is built by `parseModelPrices()` which already strips this prefix via `parseModelName()`, storing keys like `gpt-4o/openai`. However, `findModelPrice()` was not stripping the prefix at lookup time, so all four fallback attempts would fail and return `DEFAULT_COST = 0`.

Fix: call `parseModelName(modelName)` at the top of `findModelPrice()`, immediately after the blank-check guard, before any lookup attempts. This reuses the existing helper and is backwards-compatible — models without a `/` are returned unchanged.

## Change checklist
- [ ] User facing
- [ ] Documentation update

## Issues
- Resolves #5621

## Testing

New parameterized test `calculateCost_shouldStripProviderPrefix_issue5621` in `CostServiceTest` covers:
- `openai/gpt-4o` with provider `openai`
- `openai/gpt-4o-mini` with provider `openai`
- `anthropic/claude-3-5-sonnet-20241022` with provider `anthropic`
- `anthropic/claude-3-5-haiku-20241022` with provider `anthropic`

All 27 `CostServiceTest` tests pass, including pre-existing backwards-compatibility cases for exact match, dot normalization (#4114), and date-suffix stripping (#5018).

```
mvn test -Dtest="CostServiceTest" -pl apps/opik-backend
```

## Documentation

No documentation update needed.

### CODE REVIEW

File: apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java [hunk 1]
```diff
@@ -83,6 +83,10 @@ private static ModelPrice findModelPrice(String modelName, String provider) {
             return DEFAULT_COST;
         }
 
+        // Strip provider prefix if present (e.g. "openai/gpt-4o" -> "gpt-4o")
+        // LiteLLM sends model names with provider prefix via gen_ai.request.model
+        modelName = parseModelName(modelName);
```
Comment (andrescrz) [inline apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java:95]: The next logical block clearly mentions that for backwards compatibility, the exact match is tried first. This assigns the new value to `modelName`. This might fix the particular problem, but wow do we ensure this doesn't break the rest of the pricing logic below?

File: apps/opik-backend/src/test/java/com/comet/opik/domain/cost/CostServiceTest.java [hunk 2]
```diff
@@ -148,6 +148,33 @@ void calculateCost_shouldReturnZeroForUnknownModelWithDateSuffix_issue5018() {
...
+    /**
+     * Test for issue #5621: LiteLLM OTel model names with provider prefix not found in pricing table.
+     *
+     * LiteLLM sends model names with provider prefix via gen_ai.request.model
+     * (e.g. "openai/gpt-4o", "anthropic/claude-3-5-sonnet-20241022").
+     * These should be stripped before lookup to match the stored keys.
+     */
+    @ParameterizedTest
+    @MethodSource("provideModelNamesWithProviderPrefix")
+    void calculateCost_shouldStripProviderPrefix_issue5621(String modelName, String provider) {
```
Comment (andrescrz) [inline apps/opik-backend/src/test/java/com/comet/opik/domain/cost/CostServiceTest.java:167]: Related to my other comment, this test LGTM for the issue you're trying to fix. But likely you need to extend the other test cases to catch the issue I'm mentioned. I'm not sure if that's well covered in the existing tests.

File: apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java [hunk 3]
```diff
@@ -83,6 +86,14 @@ private static ModelPrice findModelPrice(String modelName, String provider) {
...
+        // Strip provider prefix if present (e.g. "openai/gpt-4o" -> "gpt-4o").
+        // LiteLLM sends model names with provider prefix via gen_ai.request.model.
+        // This is safe because parseModelPrices() also calls parseModelName() when building
+        // the price map, so stored keys never contain a provider prefix. All subsequent
+        // normalization steps (dot→hyphen, date suffix stripping) are therefore applied to
+        // the same prefix-free name that was used as the key when the map was populated.
+        modelName = parseModelName(modelName);
+
         // Try exact match first (backwards compatibility)
         String exactKey = createModelProviderKey(modelName, provider);
```
[the remark this answers is not in the document]
Comment (dsblank) [reply apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java:98]: The prefix is already stripped before this call. Line 95 reassigns the local variable: `modelName = parseModelName(modelName);`. So when `createModelProviderKey(modelName, provider)` is called at line 98, `modelName` is already prefix-free. For example, `"anthropic/claude-sonnet-4.5-2025-12-17"` becomes `"claude-sonnet-4.5-2025-12-17"` at line 95, and that prefix-free name flows through all subsequent lookup steps (exact match, dot normalisation, date-suffix stripping).

**Comment by dsblank** [comment]
@andrescrz I believe your comments have been addressed.
