### PR TITLE
[issue-5018] [BE] Add fallback logic to strip date suffixes from model names for cost calculation

### LINKED ISSUE #5018: [Bug]: GPT-5.2 costs are not tracked (total_estimated_cost is None)
### What component(s) are affected?

- [x] Opik Python SDK
- [ ] Opik Typescript SDK
- [ ] Opik Agent Optimizer SDK
- [ ] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 1.10.1

### Describe the problem

I noticed that Opik does not track costs for the gpt-5.2 model, while cost tracking works correctly for gpt-5.1 in this example (but also works for previous models like 4.1).

I tested this using the OpenAI integration (track_openai) and @track decorators. The trace for gpt-5.2 is created correctly, but total_estimated_cost is always None.

### Reproduction steps and code snippets
```python
from opik import Opik, track
from opik.integrations.openai import track_openai
from openai import OpenAI
from time import sleep

client = OpenAI()
client = track_openai(client)
opik_client = Opik(project_name="Default Project")

@track(name="gpt-5.2-try")
def call_5_2():
    response = client.responses.parse(
        model="gpt-5.2",
        input="hello tell me a joke"
    )
    return response

@track(name="gpt-5.1-try")
def call_5_1():
    response = client.responses.parse(
        model="gpt-5.1",
        input="hello tell me a joke"
    )
    return response

def get_last_trace_cost():
    traces = opik_client.search_traces(project_name="Default project")
    _cost = traces[0].total_estimated_cost
    if _cost is None:
        return "None"
    else:
        return _cost

call_5_2()
sleep(2)
print(get_last_trace_cost())

call_5_1()
sleep(2)
print(get_last_trace_cost())
```

### Error logs or stack trace

None
0.00024375

### Healthcheck results

_No response_

### PR DESCRIPTION
**Pull request by dsblank**
## Details

**This PR was generated by ollie-agent.**

Fixes issue where OpenAI returns dated model names (e.g., gpt-5.2-2025-12-17) but the pricing database only has the base model name (e.g., gpt-5.2).

Changes:
- Enhanced findModelPrice() to try stripping date suffixes (YYYY-MM-DD format) after trying exact match and normalized name lookups
- Added stripDateSuffix() method to handle date pattern removal
- Added comprehensive unit tests for the new fallback logic
- Tests verify that models like gpt-5.2-2025-12-17 correctly fall back to gpt-5.2

This ensures cost tracking works for gpt-5.2 and future dated model variants.

## Change checklist

N/A

## Issues

- Resolves #5018 

## Testing

Tests are added.

## Documentation

N/A

### CODE REVIEW

File: apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java [hunk 1]
```diff
@@ -97,6 +100,32 @@ private static ModelPrice findModelPrice(String modelName, String provider) {
             }
         }
 
+        // Try stripping date suffix from normalized name (e.g., "gpt-5-2-2025-12-17" -> "gpt-5-2")
+        String baseNormalizedModelName = stripDateSuffix(normalizedModelName);
+        if (!baseNormalizedModelName.equals(normalizedModelName)) {
```
Comment (andrescrz) [inline apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java]: A few minor points about this:
- Better to encapsulate the `toLowerCase` in `stripDateSuffix`.
- Better use `equalsIgnoreCase`.

File: apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java [hunk 2]
```diff
@@ -97,6 +100,32 @@ private static ModelPrice findModelPrice(String modelName, String provider) {
...
+                log.debug(
+                        "Found model price using normalized base name after stripping date suffix. Original: '{}', Base: '{}'",
+                        modelName, baseNormalizedModelName);
+                return baseNormalizedMatch;
+            }
+        }
+
+        // Try stripping date suffix from original name with dots preserved (e.g., "gpt-5.2-2025-12-17" -> "gpt-5.2")
+        String baseOriginalModelName = stripDateSuffix(modelName.toLowerCase(java.util.Locale.ROOT));
+        if (!baseOriginalModelName.equals(modelName.toLowerCase(java.util.Locale.ROOT))) {
```
Comment (andrescrz) [inline apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java]: Minor: 
- per my other comment, you wouldn't need the lowerCase calls here. 
- better use `.toLowerCase(Locale.ROOT)` and avoid the inlined import.

File: apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java [hunk 3]
```diff
@@ -97,6 +100,32 @@ private static ModelPrice findModelPrice(String modelName, String provider) {
...
+            String baseOriginalKey = createModelProviderKey(baseOriginalModelName, provider);
+            ModelPrice baseOriginalMatch = modelProviderPrices.get(baseOriginalKey);
+            if (baseOriginalMatch != null) {
+                log.debug(
+                        "Found model price using original base name after stripping date suffix. Original: '{}', Base: '{}'",
+                        modelName, baseOriginalModelName);
+                return baseOriginalMatch;
```
Comment (andrescrz) [inline apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java]: Minor: I'd personally revere these checks. First the check on the `stripped date model name` and then the check on the `stripped date normalized model name`. 

Renaming the method level local vars to more significant names would help (`baseNormalizedModelName` and `baseOriginalModelName`. 

In addition, inner vars such as `baseOriginalKey` and `baseOriginalMatch` could keep the original pre-existing name in this method, as they don't collide. It would be more readable.

File: apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java [hunk 4]
```diff
@@ -114,6 +143,23 @@ private static String normalizeModelName(String modelName) {
...
+     *
+     * Date patterns recognized: YYYY-MM-DD (e.g., "2025-12-17") at the end of the model name.
+     *
+     * @param modelName The model name (already normalized with hyphens and lowercase)
+     * @return Model name with date suffix removed if present, otherwise original name
+     */
+    private static String stripDateSuffix(String modelName) {
+        // Pattern: ends with -YYYY-MM-DD where YYYY is 2000-2099, MM is 01-12, DD is 01-31
+        // This is a simple heuristic that should work for most date-suffixed model names
+        String datePattern = "-\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$";
```
Comment (andrescrz) [inline apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java]: Minor: better define the regex as static final constant.

File: apps/opik-backend/src/test/java/com/comet/opik/domain/cost/CostServiceTest.java [hunk 5]
```diff
@@ -98,4 +98,46 @@ private static Stream<Arguments> provideModelNamesForNormalization() {
...
+                "prompt_tokens", 1000,
+                "completion_tokens", 500);
+
+        BigDecimal cost = CostService.calculateCost(modelName, provider, usage, null);
+
+        if (shouldHaveCost) {
+            assertThat(cost).isGreaterThan(BigDecimal.ZERO);
+        } else {
+            assertThat(cost).isEqualTo(BigDecimal.ZERO);
+        }
```
Comment (andrescrz) [inline apps/opik-backend/src/test/java/com/comet/opik/domain/cost/CostServiceTest.java]: Minor: test for cost zero (not found) should be a separated test. Having if statements for assertions is a bad practice.

File: apps/opik-backend/src/test/java/com/comet/opik/domain/cost/CostServiceTest.java [hunk 6]
```diff
@@ -98,4 +98,46 @@ private static Stream<Arguments> provideModelNamesForNormalization() {
...
+                Arguments.of("gpt-5.2-2026-01-15", "openai", true),
+                Arguments.of("gpt-5.1-2025-11-13", "openai", true),
+                Arguments.of("GPT-5.2-2025-12-17", "openai", true),
+
+                // Base models should still work
+                Arguments.of("gpt-5.2", "openai", true),
+                Arguments.of("gpt-5.1", "openai", true),
+
+                // Dot notation with date suffix
+                Arguments.of("gpt-5.2-2025-12-17", "openai", true),
```
Comment (andrescrz) [inline apps/opik-backend/src/test/java/com/comet/opik/domain/cost/CostServiceTest.java]: Minor: there's a lot of duplicated tests while testing stripping date with normalized name is still missing.  The legimate tests here are:
1. stripped date on original name. 
2. stripped date on normalized name.
3. base models should work.

File: apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java [hunk 7]
```diff
@@ -111,7 +142,21 @@ private static ModelPrice findModelPrice(String modelName, String provider) {
      * @return Normalized model name with dots replaced by hyphens and lowercase
      */
     private static String normalizeModelName(String modelName) {
-        return modelName.replace('.', '-').toLowerCase(java.util.Locale.ROOT);
+        return modelName.replace('.', '-').toLowerCase(Locale.ROOT);
+    }
+
+    /**
+     * Strips date suffixes from model names to enable fallback pricing lookup.
```
[the remark this answers is not in the document]
Comment (andrescrz) [reply apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java:149]: This comments makes sense. It'd be nice to centralise the logic in a single method, instead of having them duplicated. Anyway, this is an optional improvement and not a blocker.

File: apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java [hunk 8]
```diff
@@ -111,7 +142,21 @@ private static ModelPrice findModelPrice(String modelName, String provider) {
...
+     * but the pricing database only has the base model name (e.g., "gpt-5.2").
+     *
+     * Date patterns recognized: YYYY-MM-DD (e.g., "2025-12-17") at the end of the model name.
+     *
+     * @param modelName The model name
+     * @return Lowercase model name with date suffix removed if present, otherwise lowercase original name
+     */
+    private static String stripDateSuffix(String modelName) {
+        return modelName.toLowerCase(Locale.ROOT).replaceFirst(DATE_SUFFIX_PATTERN, "");
     }
```
[the remark this answers is not in the document]
Comment (andrescrz) [reply apps/opik-backend/src/main/java/com/comet/opik/domain/cost/CostService.java:160]: This is a nice performance improvement, but not a blocker in my view. It's optional.

File: apps/opik-backend/src/test/java/com/comet/opik/domain/cost/CostServiceTest.java [hunk 9]
```diff
@@ -98,4 +98,38 @@ private static Stream<Arguments> provideModelNamesForNormalization() {
...
+    @Test
+    void calculateCost_shouldReturnZeroForUnknownModelWithDateSuffix_issue5018() {
+        Map<String, Integer> usage = Map.of(
+                "prompt_tokens", 1000,
+                "completion_tokens", 500);
+
+        BigDecimal cost = CostService.calculateCost("unknown-model-2025-12-17", "openai", usage, null);
+
+        assertThat(cost).isEqualTo(BigDecimal.ZERO);
+    }
```
[the remark this answers is not in the document]
Comment (andrescrz) [reply apps/opik-backend/src/test/java/com/comet/opik/domain/cost/CostServiceTest.java:123]: This is correct, but not a blocker in my view.
